from .solution import SolveDay11x1, SolveDay11x2

text_input = """
...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....
"""


def test_solution_1():
    assert SolveDay11x1(True).solve(text_input) == 374


def test_solution_2():
    assert SolveDay11x2(True).solve(text_input) == 0
